### ISSUE TITLE
evaluation (AP) does not change

### ISSUE THREAD

**Issue by kcrumb** [google/automl#660] opened 2020-08-08 12:20 UTC
I am trying to train my custom dataset with the new pretrained models, but the evaluation at each epoch stays the same (from the beginning) and does not change at all. E.g.
```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.002
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.008
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.001
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.004
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.015
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.063
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.111
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.052
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.073
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.189
```

I'm using the same dataset which I used for the old pretrained model. I'm at epoch 205 and Tenorboard doesn't update the progress (only show steps for the first epoch). Because evluation values do not improve?
![image](https://user-images.githubusercontent.com/4051421/89710248-7549c980-d981-11ea-9c12-fa0a8038ce73.png)

Does anyone have any idea what could be causing it? Are there some new settings that I am missing?
I'm using TF-2.3.0, also tried TF-2.1.1. I also tried the old pretrained model and I have the most current repo code. Nothing works for me.

### My params:
```
python3 ~/projects/automl-efficientdet/efficientdet/main.py \
        --mode=train_and_eval \
        --training_file_pattern=/datasets/split_train_bb.tfrecord/p*.tfrecord \
        --validation_file_pattern=/datasets/split_val_bb.tfrecord/p*.tfrecord \
        --model_name='efficientdet-d0' \
        --model_dir=/automl-efficientdet/logs/efficientdet-d0.v1 \
        --ckpt=/automl-efficientdet/pretrained.v2/efficientdet-d0 \
        --train_batch_size=16 \
        --eval_batch_size=1 \
        --eval_samples=1000 \
        --num_examples_per_epoch=11064 \
        --num_epochs=300 \
        --hparams=config_1.yaml \
```
config_1.yaml
```
num_classes: 2
learning_rate: 0.002
lr_warmup_init: 0.0002
var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'
label_id_mapping: {0: background, 1: polyp}
jitter_min: 0.8
jitter_max: 1.2
```

**Comment by vinhdc10998** [comment] 2020-08-11 04:51
Are u have an answer to this? I have same problem.

**Comment by kcrumb** [comment] 2020-08-11 11:30
@vinhdc10998 No, sorry. Didn't found a solution yet. Even tried to go some commits back to isolate the problem, since the early version worked for me. Please let me know if you found a solution or just a clue.

**Comment by mingxingtan** [comment] 2020-08-11 18:47
This is strange, let me give it a try with pascal voc.

**Comment by kcrumb** [comment] 2020-08-13 00:39
Thank you for your time! Let me know if you can reproduce this behaviour or have a idea what it could be.

**Comment by mingxingtan** [comment] 2020-08-14 04:15
this bug is caused by https://github.com/google/automl/issues/666  (due to a bug, it only train the first epoch).
The bug has been fixed in https://github.com/google/automl/commit/a126efd5f0d17a8b7e9a1688887c02ed1f97ff48

**Closed by mingxingtan** 2020-08-14 04:15 UTC
