### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by gengyanlei** [google/automl#165] opened 2020-04-07 02:54 UTC
I have 4 graphics cards, pass "gpus = tf.config.experimental.list_physical_devices ('GPU')
tf.config.experimental.set_visible_devices (devices = gpus [0], device_type = 'GPU') "Set to use 1 graphics card, but an error occurs when running according to the parameters:
ValueError: in converted code:
  /home/gengyanlei/Python_work/automl/efficientdet/backbone/efficientnet_model.py:637 call *
         outputs = self._relu_fn (
     /usr/local/lib/python3.6/site-packages/tensorflow_core/python/layers/base.py:548 __call__
         outputs = super (Layer, self) .__ call __ (inputs, * args, ** kwargs)
     /usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py:812 __call__
         self.name)
     /usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/input_spec.py:177 assert_input_compatibility
         str (x.shape.as_list ()))

     ValueError: Input 0 of layer conv2d_1 is incompatible with the layer: expected ndim = 4, found ndim = 1. Full shape received: [0]

**Comment by mingxingtan** [comment] 2020-04-07 05:47
Looks like the problem is from you data, not related to GPUs.

The input image should have dimenion of 4 such as [N, H, W, C], but the actual input is dimension of [0].

**Comment by gengyanlei** [comment] 2020-04-07 06:26
Okay thank you.
I haven't used tensorflow for a long time, and tf2.0 is unfamiliar.

**Comment by mingxingtan** [comment] 2020-04-07 23:29
I am going to close this issue for now, but feel free to reopen it if you still have problems.

**Closed by mingxingtan** 2020-04-07 23:29 UTC
