### ISSUE TITLE
InvalidArgumentError: Invalid device ordinal value (1). Valid range is [0, 0]. 	while setting up XLA_GPU_JIT device number 1

### ISSUE THREAD

**Issue by Sean0123456789** [google/automl#111] opened 2020-03-31 03:14 UTC
When I run tutorial or inference.py, met this problem. Anyone can help?

**Comment by mingxingtan** [comment] 2020-03-31 05:31
I just reran the tutorial in colab and did not have any problem. Looks like it might your environment. Could you verify your setups by running  some simple tensorflow code first? Thanks!

**Comment by mingxingtan** [comment] 2020-03-31 17:31
I am going to close this issue since I am not able to reproduce it.

**Closed by mingxingtan** 2020-03-31 17:31 UTC
